### ISSUE TITLE
Bug: Incorrect Recipe Data Population

### ISSUE THREAD

**Issue by collette-tamez** [Learning-Fuze/C9_recipe_finder#27]
I've come across a few cases where a recipe will not have any data in the "Recipe How To" section and will instead populate that area with data from the previous recipe looked at by the user. 

Notice the empty "How to Section"
![screen shot 2016-09-05 at 10 10 41 pm](https://cloud.githubusercontent.com/assets/8095841/18262450/759f3d6e-73b6-11e6-9ddb-715aeb58263d.png)

I then viewed a different recipe
![screen shot 2016-09-05 at 10 23 03 pm](https://cloud.githubusercontent.com/assets/8095841/18262541/651d2432-73b7-11e6-8bef-1d11fa1e67bf.png)

When I return to the first recipe with empty instructions section there is now data there from the previously viewed recipe 
![screen shot 2016-09-05 at 10 23 13 pm](https://cloud.githubusercontent.com/assets/8095841/18262551/842c7800-73b7-11e6-91ec-9ed5deb86e39.png)

**Comment by rosemariegonzales** [comment]
I fixed this one and sent a pull request for review.

**Comment by collette-tamez** [comment]
Can confirm fix, issue no longer occurring. Nice work.
