### ISSUE TITLE
Cook Time Drop Down Menu

### ISSUE THREAD

**Issue by collette-tamez** [Learning-Fuze/C9_recipe_finder#29]
One of the options in the "cook time"  is "5-60" minutes. Should read "45-60"
![screen shot 2016-09-05 at 10 02 45 pm](https://cloud.githubusercontent.com/assets/8095841/18262780/7ccee4ce-73b9-11e6-8b61-12ebf797708c.png)

**Comment by rosemariegonzales** [comment]
I changed the typo and sent a pull request.

**Comment by collette-tamez** [comment]
Confirmed fix, issue not longer occurring. Closing ticket.
