### ISSUE TITLE
Cook Time Results Need to Be Reviewed

### ISSUE THREAD

**Issue by rosemariegonzales** [Learning-Fuze/C9_recipe_finder#35]
When I clicked on 45-60 min of cook time, the results included 35 min recipes:

![image](https://cloud.githubusercontent.com/assets/19966888/18291152/50c7ca76-743b-11e6-9869-8dc7570cbff4.png)

**Comment by collette-tamez** [comment]
No longer seeing issue occur. Ready to be closed @rosemariegonzales

**Comment by rosemariegonzales** [comment]
Thanks for reviewing @collette-tamez. I'll close this issue now.
